---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
---

Welcome to my research website.

* [DSC query code](dscquery.html)

* [SuSiE z convergence](SusieZConverge.html)

* [SuSiE z Problem](SusieZProblem.html)

* [Problem 75](Problem75.html)

* [Problem 475](Problem475.html)

* [SuSiE z estimate prior variance comparison](SusieZPriorVarCompare.html)

    [SuSiE estimate prior variance comparison](SusiePriorVarCompare.html)

* [SuSiE z comparisons R full rank](SusieZPerformance.html)

  [SuSiE z vs DAP Power in one data set](SuSiEDAP_Power_data31_35.html)
  
* [SuSiE z comparisons R singular](SusieZPerformanceRE8.html)
    
    [Problem 42](SuSiEzRProblem42.html)

    [SuSiE z comparisons R singular with truncated eigenvalues](SusieZPerformanceRE3.html)
    
    [Problem 92](SuSiEzRProblem92.html)
    
* [SuSiE Robust](SuSiERobust.html)

* SuSiE z investigation:
    
    [log Bays Factor](logBF.html)
    
    [Investigate](Investigate.html)
    
    [Doesn't stop problem](DontStopProblem.html)

* Comparing result from in-sample R vs out-sample R:

    Most recent result: 
    
    2019-10： The simulation is using [dsc-finemap](https://github.com/stephenslab/dsc-finemap/blob/master/susie_rss_paper.dsc).

      * [lambda = 0](SuSiERSS_dsc_susiersspaper_results_lamb0.html)

      * [lambda = 0.1](SuSiERSS_dsc_susiersspaper_results_lamb0.1.html)

      * [lambda = 1](SuSiERSS_dsc_susiersspaper_results_lamb1.html)

    L = 5:

      * [lambda = 0](SuSiERSS_dsc_susiersspaper_results_lamb0_L5.html)
      
      * [lambda = $10^{-4}$](SuSiERSS_dsc_susiersspaper_results_lamb1e-4_L5.html)

      * [lambda = 0.1](SuSiERSS_dsc_susiersspaper_results_lamb0.1_L5.html)

      * [lambda = 1](SuSiERSS_dsc_susiersspaper_results_lamb1_L5.html)
    
    -----------------------------------------------------------------------
    
    More investigations (2019-06-16): we use FINEMAP from v1.1, including MAF threshold 5%.
    
    [Power, FDR for FINEMAP and SuSiE related methods](r_compare_add_z_lambda_caviar_maf_susie.html)
    
    [Calibrated PIP and ROC for CAVIAR](r_compare_add_z_lambda_caviar_maf_CAVIAR_ROC.html)
    
    [Calibrated PIP and ROC for FINEMAP](r_compare_add_z_lambda_caviar_maf_FINEMAP_ROC.html)
    
    [Calibrated PIP and ROC for SuSiE b](r_compare_add_z_lambda_caviar_maf_susieb_ROC.html)
    
    [Calibrated PIP and ROC for SuSiE rss](r_compare_add_z_lambda_caviar_maf_susierss_ROC.html)
    
    [ROC in one plot](r_compare_add_z_lambda_caviar_maf_ROC.html)
    
    -----------------------------------------------------------------------

    More investigations (2019-05-06): we change FINEMAP from v1.1 to v1.3.1, add CAVIAR
    
    [Power, FDR for FINEMAP and SuSiE related methods](r_compare_add_z_lambda_caviar_susie_finemap.html)
    
    [Calibrated PIP and ROC for CAVIAR](r_compare_add_z_lambda_caviar_CAVIAR.html)
    
    [Calibrated PIP and ROC for FINEMAP](r_compare_add_z_lambda_caviar_FINEMAP_ROC.html)
    
    [Calibrated PIP and ROC for SuSiE b](r_compare_add_z_lambda_caviar_susieb_ROC.html)
    
    [Calibrated PIP and ROC for SuSiE rss](r_compare_add_z_lambda_caviar_susierss_ROC.html)
    
    [ROC in one plot](r_compare_add_z_lambda_caviar_ROC.html)

    [Data 1](r_compare_add_z_lambda_caviar_Eg1.html)
    
    [Compute log-BF for CAVIAR](bf_test_caviar.html)
    
    ------------------------------------------------------------------------
    
    More investigations (2019-04-29): we include model 1. without estimating residual variance, 2. susierss with lambda
    
    [Power, FDR for SuSiE related methods](r_compare_add_z_lambda_susie.html)
    
    [Calibrated PIP and ROC for FINEMAP](r_compare_add_z_lambda_finemap.html)
    
    [Calibrated PIP and ROC for SuSiE b](r_compare_add_z_lambda_susieb_ROC.html)
    
    [Calibrated PIP and ROC for SuSiE rss](r_compare_add_z_lambda_susierss_ROC.html)
    
    [ROC in one plot](r_compare_add_z_lambda_ROC.html)
    
    ------------------------------------------------------------------------
    
    More investigations (2019-04-25): we include another estimation of correlation matrix cov2cor($X'X + zz'$)
    
    [Power, FDR for SuSiE related methods](r_compare_add_z_susie.html)
    
    [Calibrated PIP and ROC for FINEMAP](r_compare_add_z_finemap.html)
    
    [Calibrated PIP and ROC for SuSiE](r_compare_susie_ROC.html)
    
    [Calibrated PIP and ROC for SuSiE b](r_compare_add_z_susieb_ROC.html)
    
    [Calibrated PIP and ROC for SuSiE rss](r_compare_add_z_susierss_ROC.html)
    
    [ROC in one plot](r_compare_add_z_ROC.html)
    
    ------------------------------------------------------------------------
    
    [Equal effect size](r_compare_susie_equal.html)
    
    [NON-Equal effect size](r_compare_susie_notequal.html)
    
    [Calibrated PIP and ROC for FINEMAP](r_compare_finemap.html)
    
    [Calibrated PIP and ROC for SuSiE b (equal effect size)](r_compare_susieb_ROC.html)
    
    [Calibrated PIP and ROC for SuSiE rss (equal effect size)](r_compare_susierss_ROC.html)
    
    + Problem data: 
        
        [SuSiE bhat out sample R error](r_compare_susieb_problem.html)
      
        [SuSiE RSS not converge](SuSiErssNotConverge.html)
    
    
* A [Benchmark](FINEMAP_benchmark.html) for FINEMAP v1.3.1

