---
title: "log BF calculation"
author: "Yuxin Zou"
date: "3/12/2019"
output: 
  workflowr::wflow_html:
    code_folding: hide
---

```{r message=FALSE}
library(susieR)
library(R.utils)
library(mvtnorm)
sourceDirectory('~/Documents/GitHub/susieR/inst/code/susiez_num/')
```

Using N3finemapping from susieR, we run susie model with lambda 1e-8.
```{r eval=FALSE}
data(N3finemapping)
b <- N3finemapping$data$true_coef[,1]
R <- cor(N3finemapping$dat$X)
z_scores = N3finemapping$sumstats[1,,1]/N3finemapping$sumstats[2,,1]
fit_lbf = susie_z_general_num(z_scores, R, L=1, max_iter = 1, lambda = 0.1, estimate_prior_method = 'EM')
```

The head of log BF from mvtnorm build-in function is 
```
0.06449783 -0.36519030 -0.09638240 -0.08256167 -0.25397378 -0.31992161
```

The head of log BF from our computation is 
```
0.22989997 -0.09115324  0.05552693  0.04863540 -0.09050853 -0.09024205
```

If we run susie model with lambda = 0.1, the log BF from mvtnorm build-in function is same as log BF from our computation.

The head of it is 
```
0.24190347 -0.08910697  0.06196027  0.05362330 -0.08647301 -0.08434728
```



