---
title: "Compare in-sample R vs out-sample R (equal effect) FINEMAP"
author: "Yuxin Zou"
date: "4/15/2019"
output: 
  workflowr::wflow_html:
    code_folding: hide
---

```{r}
library(ggplot2)
library(cowplot)
library(gridExtra)
```

```{r}
dscout = readRDS('output/r_compare_dscout_susie_finemappip_truth_tibble.rds')
dscout$method = rep('susie_b', nrow(dscout))
dscout$method[!is.na(dscout$susie_z.ld_method)] = 'susie_rss'
dscout$method[!is.na(dscout$finemap.ld_method)] = 'finemap'

dscout$ld_method = dscout$susie_bhat.ld_method
dscout$ld_method[!is.na(dscout$susie_z.ld_method)] = dscout$susie_z.ld_method[!is.na(dscout$susie_z.ld_method)]
dscout$ld_method[!is.na(dscout$finemap.ld_method)] = dscout$finemap.ld_method[!is.na(dscout$finemap.ld_method)]
dscout = dscout[,-c(6,8,9,10)]
dscout$sim_gaussian.effect_weight[which(dscout$sim_gaussian.effect_weight == 'rep(1/n_signal, n_signal)')] = 'equal'
dscout$sim_gaussian.effect_weight[which(dscout$sim_gaussian.effect_weight != 'equal')] = 'notequal'
colnames(dscout) = c('DSC', 'meta', 'pve', 'n_signal', 'effect_weight', 'N_in', 'total', 'valid', 'size', 'purity', 'top', 'converged', 'pip', 'method', 'ld_method')
```

## ALL

```{r}
dscout.finemap = dscout[dscout$method == 'finemap',-c(7,8,9,10,11,12)]
dscout.equal.finemap = dscout.finemap[dscout.finemap$effect_weight == 'equal',]
dscout.equal.finemap.list = list('in_sample' = dscout.equal.finemap[dscout.equal.finemap$ld_method == 'in_sample',],
                                 'out_sample' = dscout.equal.finemap[dscout.equal.finemap$ld_method == 'out_sample',])
```

```{r eval=FALSE}
dat = list('in_sample'=matrix(NA, 0, 2), 'out_sample'=matrix(NA, 0, 2))
for(Rtype in names(dat)){
  for(j in 1:nrow(dscout.equal.finemap.list[[Rtype]])){
    datj = cbind(dscout.equal.finemap.list[[Rtype]]$pip[[j]], dscout.equal.finemap.list[[Rtype]]$meta[[j]]$true_coef)
    dat[[Rtype]] = rbind(dat[[Rtype]], datj)
  }
  colnames(dat[[Rtype]]) = c('pip', 'truth')
}
# saveRDS(dat, '../output/r_compare_FINEMAP_PIP_ROC.rds')
```

```{r}
dat = readRDS('output/r_compare_FINEMAP_PIP_ROC.rds')
```

```{r}
bin_size = 20
bins = cbind(seq(1:bin_size)/bin_size-1/bin_size, seq(1:bin_size)/bin_size)

pip_cali = list('in_sample'=matrix(NA, nrow(bins), 3), 'out_sample'=matrix(NA, nrow(bins), 3))
for(Rtype in names(pip_cali)){
  for (i in 1:nrow(bins)) {
    data_in_bin = dat[[Rtype]][which(dat[[Rtype]][,1] > bins[i,1] & dat[[Rtype]][,1] < bins[i,2]),, drop=FALSE]
    pip_cali[[Rtype]][i,1] = sum(data_in_bin[,'pip'])
    pip_cali[[Rtype]][i,2] = sum(data_in_bin[,'truth'])
    pip_cali[[Rtype]][i,3] = nrow(data_in_bin)
  }
}

for(Rtype in names(pip_cali)){
  pip_cali[[Rtype]][,c(1,2)] = pip_cali[[Rtype]][,c(1,2)] / pip_cali[[Rtype]][,3]
}

```

```{r}
dot_plot = function(dataframe) {
  ggplot(dataframe, aes(x=mean_pip, y=observed_freq)) + 
    geom_errorbar(aes(ymin=observed_freq-se, ymax=observed_freq+se), colour="gray", size = 0.2, width=.01) + 
    geom_point(size=1.5, shape=21, fill="#002b36") + # 21 is filled circle 
    xlab("Mean PIP") +
    ylab("Observed frequency") +
    coord_cartesian(ylim=c(0,1), xlim=c(0,1)) +
    geom_abline(slope=1,intercept=0,colour='red', size=0.2) +
    expand_limits(y=0) +                        # Expand y range
    theme_cowplot()
}
```

### Calibrated PIP

```{r fig.width=10, fig.height=5,fig.align='center'}
g = list()
idx = 0
for(Rtype in names(pip_cali)){
  idx = idx + 1
  pip_cali[[Rtype]][,3] = sqrt(pip_cali[[Rtype]][,2] * (1 - pip_cali[[Rtype]][,2]) / pip_cali[[Rtype]][,3]) * 2
  pip_cali[[Rtype]] = as.data.frame(pip_cali[[Rtype]])
  colnames(pip_cali[[Rtype]]) = c("mean_pip", "observed_freq", "se")
  g[[Rtype]] = dot_plot(pip_cali[[Rtype]]) + ggtitle(Rtype)
}
grid.arrange(g[[1]], g[[2]], nrow = 1)
```

### ROC

```{r}
pip_cutoff = 0.05

roc_data = function(d1, cutoff = c(pip_cutoff, 0.999), connect_org = T) {
  grid = 500
  ttv = seq(1:grid)/grid
  ttv = ttv[which(ttv>=cutoff[1] & ttv<=cutoff[2])]
  rst1 = t(sapply(ttv, function(x) c(sum(d1[,2][d1[,1]>=x]), length(d1[,2][d1[,1]>=x]))))
  rst1 = cbind(rst1, sum(d1[,2]))
  rst1 = as.data.frame(rst1)
  colnames(rst1) = c('true_positive', 'total_positive', 'total_signal')
  rst2 = as.data.frame(cbind(rst1$true_positive / rst1$total_positive, rst1$true_positive / rst1$total_signal,  ttv))
  if (connect_org) {
    # make a stair to origin
    rst2 = rbind(rst2, c(max(0.995, rst2[nrow(rst2),1]), max(rst2[nrow(rst2),2]-0.01, 0), rst2[nrow(rst2),3]))
    rst2 = rbind(rst2, c(1, 0, 1))
  }
  colnames(rst2) = c('Precision', 'Recall', 'Threshold')
  return(list(counts = rst1, rates = rst2))
}

print("Computing ROC data ...")
roc = list()
for (method in names(dat)) {
  roc[[method]] = roc_data(dat[[method]])
}
```

```{r fig.width=6, fig.height=5}
chunks = 0
smooth = FALSE
colors = c('#A60628', '#7A68A6', '#348ABD', '#467821', '#FF0000', '#188487', '#E2A233','#A9A9A9', '#000000', '#FF00FF', '#FFD700', '#ADFF2F', '#00FFFF')
library(scam)
create_chunks = function(item, n) {
  splitted = suppressWarnings(split(item, 1:n))
  return(c(splitted[[1]], splitted[[length(splitted)]][length(splitted[[length(splitted)]])]))
}
make_smooth = function(x,y,subset=chunks, smooth = FALSE){
  if (smooth) {
    if (subset < length(x) && subset > 0) {
      x = create_chunks(x, subset)
      y = create_chunks(y, subset)
    }
    dat = data.frame(cbind(x,y))
    colnames(dat) = c('x','y')
    y=predict(scam(y ~ s(x, bs = "mpi"), data = dat))
    }
  return(list(x=x,y=y))
}
add_text = function(thresholds,x,y,threshold,color,delta = -0.06) {
  idx = which(thresholds == threshold)
  text(x[idx] - delta,y[idx],labels = threshold,col = color,cex = 0.8)
  points(x[idx], y[idx])
}
labels = vector()
i = 1
for (method in names(roc)) {
  yy = make_smooth(1 - roc[[method]]$rates$Precision, roc[[method]]$rates$Recall)
  if (i == 1) {
    plot(yy$x, yy$y, t="l", col=colors[i], ylab = "power", xlab ="FDR", main = 'ROC', bty='l', lwd = 2, xlim = c(0,0.8), ylim = c(0,0.8))
  } else {
    lines(yy$x, yy$y, col=colors[i], lwd = 2, xlim = c(0,0.8), ylim = c(0,0.8))
  }
  #add_text(dat[[method]]$rates$Threshold, yy$x, yy$y, 0.9, colors[i])
  add_text(roc[[method]]$rates$Threshold, yy$x, yy$y, 0.95, colors[i])
  labels[i] = method
  i = i + 1
}
legend("topright", legend=labels, col=colors[1:i], lty=c(1,1,1), cex=0.8)

```

## PVE per signal <= 0.2

```{r}
dscout.equal.finemap = dscout.equal.finemap[dscout.equal.finemap$pve/dscout.equal.finemap$n_signal <= 0.2,]
dscout.equal.finemap.list = list('in_sample' = dscout.equal.finemap[dscout.equal.finemap$ld_method == 'in_sample',],
                                 'out_sample' = dscout.equal.finemap[dscout.equal.finemap$ld_method == 'out_sample',])
```

```{r eval=FALSE}
dat = list('in_sample'=matrix(NA, 0, 2), 'out_sample'=matrix(NA, 0, 2))
for(Rtype in names(dat)){
  for(j in 1:nrow(dscout.equal.finemap.list[[Rtype]])){
    datj = cbind(dscout.equal.finemap.list[[Rtype]]$pip[[j]], dscout.equal.finemap.list[[Rtype]]$meta[[j]]$true_coef)
    dat[[Rtype]] = rbind(dat[[Rtype]], datj)
  }
  colnames(dat[[Rtype]]) = c('pip', 'truth')
}
```

```{r}
bin_size = 20
bins = cbind(seq(1:bin_size)/bin_size-1/bin_size, seq(1:bin_size)/bin_size)

pip_cali = list('in_sample'=matrix(NA, nrow(bins), 3), 'out_sample'=matrix(NA, nrow(bins), 3))
for(Rtype in names(pip_cali)){
  for (i in 1:nrow(bins)) {
    data_in_bin = dat[[Rtype]][which(dat[[Rtype]][,1] > bins[i,1] & dat[[Rtype]][,1] < bins[i,2]),, drop=FALSE]
    pip_cali[[Rtype]][i,1] = sum(data_in_bin[,'pip'])
    pip_cali[[Rtype]][i,2] = sum(data_in_bin[,'truth'])
    pip_cali[[Rtype]][i,3] = nrow(data_in_bin)
  }
}

for(Rtype in names(pip_cali)){
  pip_cali[[Rtype]][,c(1,2)] = pip_cali[[Rtype]][,c(1,2)] / pip_cali[[Rtype]][,3]
}

```

### Calibrated PIP

```{r fig.width=10, fig.height=5,fig.align='center'}
g = list()
idx = 0
for(Rtype in names(pip_cali)){
  idx = idx + 1
  pip_cali[[Rtype]][,3] = sqrt(pip_cali[[Rtype]][,2] * (1 - pip_cali[[Rtype]][,2]) / pip_cali[[Rtype]][,3]) * 2
  pip_cali[[Rtype]] = as.data.frame(pip_cali[[Rtype]])
  colnames(pip_cali[[Rtype]]) = c("mean_pip", "observed_freq", "se")
  g[[Rtype]] = dot_plot(pip_cali[[Rtype]]) + ggtitle(Rtype)
}
grid.arrange(g[[1]], g[[2]], nrow = 1)
```

### ROC

```{r}
print("Computing ROC data ...")
roc = list()
for (method in names(dat)) {
  roc[[method]] = roc_data(dat[[method]])
}
```

```{r fig.width=6, fig.height=5}
labels = vector()
i = 1
for (method in names(roc)) {
  yy = make_smooth(1 - roc[[method]]$rates$Precision, roc[[method]]$rates$Recall)
  if (i == 1) {
    plot(yy$x, yy$y, t="l", col=colors[i], ylab = "power", xlab ="FDR", main = 'ROC', bty='l', lwd = 2, xlim = c(0,0.8), ylim = c(0,0.8))
  } else {
    lines(yy$x, yy$y, col=colors[i], lwd = 2, xlim = c(0,0.8), ylim = c(0,0.8))
  }
  #add_text(dat[[method]]$rates$Threshold, yy$x, yy$y, 0.9, colors[i])
  add_text(roc[[method]]$rates$Threshold, yy$x, yy$y, 0.95, colors[i])
  labels[i] = method
  i = i + 1
}
legend("topright", legend=labels, col=colors[1:i], lty=c(1,1,1), cex=0.8)

```
