---
title: "Untitled"
author: "Yuxin Zou"
date: "5/8/2019"
output: html_document
---

```{r}
library(data.table)
library(susieR)
```

PVE 0.2, n signal = 1

```{r}
data = readRDS('output/SuSiEFD/small_data_121.rds')
r.in = as.matrix(fread('output/SuSiEFD/small_data_121.ld_in_file.in.ld'))
r.out = as.matrix(fread('output/SuSiEFD/small_data_121.ld_out_file.out.ld'))
sim = readRDS('output/SuSiEFD/small_data_121_sim_gaussian_2.rds')
ss = readRDS('output/SuSiEFD/small_data_121_sim_gaussian_2_get_sumstats_1.rds')
```

```{r}
z = ss$sumstats$bhat/ss$sumstats$shat
r.out.addz = cov2cor((data$N_out-1) * r.out+tcrossprod(z))
susie_plot(z, y='z', b = sim$meta$true_coef)
```

## SuSiE bhat

In sample:
```{r}
fit_susiebhat_in = susie_bhat(ss$sumstats$bhat, ss$sumstats$shat, R = r.in, n = data$N_in, estimate_residual_variance = FALSE, L=5)
susie_plot(fit_susiebhat_in, y='PIP', b = sim$meta$true_coef)
```

Out sample:
```{r}
fit_susiebhat_out = susie_bhat(ss$sumstats$bhat, ss$sumstats$shat, R = r.out, n = data$N_in, estimate_residual_variance = FALSE, L=5)
susie_plot(fit_susiebhat_out, y='PIP', b = sim$meta$true_coef)
```

Out sample addz:
```{r}
fit_susiebhat_out_addz = susie_bhat(ss$sumstats$bhat, ss$sumstats$shat, R = r.out.addz, n = data$N_in, estimate_residual_variance = FALSE, L=5)
susie_plot(fit_susiebhat_out_addz, y='PIP', b = sim$meta$true_coef)
```

## SuSiE rss

In sample:
```{r}
fit_susierss_in = susie_rss(z, R = r.in, estimate_residual_variance = FALSE, L=5, lambda = 0.1)
susie_plot(fit_susierss_in, y='PIP', b = sim$meta$true_coef)
```

Out sample:
```{r}
fit_susierss_out = susie_rss(z, R = r.out, estimate_residual_variance = FALSE, L=5, lambda=2)
susie_plot(fit_susierss_out, y='PIP', b = sim$meta$true_coef)
```

Out sample addz:
```{r}
fit_susierss_out_addz = susie_rss(z, R = r.out.addz, estimate_residual_variance = FALSE, L=5, lambda = 0.1)
susie_plot(fit_susiebhat_out_addz, y='PIP', b = sim$meta$true_coef)
```
